// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4c8ESTY94JPSlsFrS1QgYQ0FhQ6-NDss',
    appId: '1:505510488974:web:d40d403331dd9ce1b4d2df',
    messagingSenderId: '505510488974',
    projectId: 'proyecto-final-bd-e1fc9',
    authDomain: 'proyecto-final-bd-e1fc9.firebaseapp.com',
    storageBucket: 'proyecto-final-bd-e1fc9.firebasestorage.app',
    measurementId: 'G-NEJLY7JVT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG7uSfHvdtWrXTmMnsbruQrkkMhQ0Ngpc',
    appId: '1:505510488974:android:60e24eea2f839e8ab4d2df',
    messagingSenderId: '505510488974',
    projectId: 'proyecto-final-bd-e1fc9',
    storageBucket: 'proyecto-final-bd-e1fc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFqAzFjritUlpOF2BA3QVoyyzm6Wmxa2U',
    appId: '1:505510488974:ios:90e42e076f7a7069b4d2df',
    messagingSenderId: '505510488974',
    projectId: 'proyecto-final-bd-e1fc9',
    storageBucket: 'proyecto-final-bd-e1fc9.firebasestorage.app',
    androidClientId: '505510488974-cvrlgnmmg3d7fsr5o3jpas2v8jg1macj.apps.googleusercontent.com',
    iosClientId: '505510488974-f3nvhcsklb1q3mm6ruugn5bf0nri12o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarea7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFqAzFjritUlpOF2BA3QVoyyzm6Wmxa2U',
    appId: '1:505510488974:ios:90e42e076f7a7069b4d2df',
    messagingSenderId: '505510488974',
    projectId: 'proyecto-final-bd-e1fc9',
    storageBucket: 'proyecto-final-bd-e1fc9.firebasestorage.app',
    androidClientId: '505510488974-cvrlgnmmg3d7fsr5o3jpas2v8jg1macj.apps.googleusercontent.com',
    iosClientId: '505510488974-f3nvhcsklb1q3mm6ruugn5bf0nri12o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarea7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4c8ESTY94JPSlsFrS1QgYQ0FhQ6-NDss',
    appId: '1:505510488974:web:dbfade65341cea63b4d2df',
    messagingSenderId: '505510488974',
    projectId: 'proyecto-final-bd-e1fc9',
    authDomain: 'proyecto-final-bd-e1fc9.firebaseapp.com',
    storageBucket: 'proyecto-final-bd-e1fc9.firebasestorage.app',
    measurementId: 'G-XZZRR8T42H',
  );

}